# Generated by Django 6.0.7 on 2026-08-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
