# Generated by Django 6.0.7 on 2026-08-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0002_product_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
