# Generated by Django 6.0.7 on 2026-08-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
