# Generated by Django 6.0.7 on 2026-08-14 02:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='default_avatar_woxm90', max_length=255, verbose_name='avatar'),
        ),
    ]
