# Generated by Django 6.0.7 on 2026-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0009_productvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='min_stock',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
