# Generated by Django 6.0.7 on 2026-08-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0010_productvariant_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
