# Generated by Django 6.0.7 on 2026-08-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0012_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
