# Generated by Django 6.0.7 on 2026-08-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0013_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='title',
        ),
    ]
