# Generated by Django 6.0.7 on 2026-09-14 00:06

import FashionStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionStore', '0016_discount_order_discount_amount_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=models.CharField(default=FashionStore.models.generate_discount_id, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=FashionStore.models.generate_order_code, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
